#Server configuration
server:
  port: 8080
  
  
  
#Eureka configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
spring:
  application:
    name: lern-gateway          
  cloud:
    gateway:
      routes:
      - id: lern-user
        uri: lb://lern-user
        predicates:
          - Path=/user-api/**
         